#> lib:text/core/load
# Generated by scripts/text/generate_widths.cjs
# @within function core:load_once

# 版が変わった場合だけ文字幅表を更新する
    execute if data storage lib:text_fonts {Version:"3564394154134fd495c2ecf79b0cd9c9177d86b20fa8663e67d3cc437db2c87f"} run return 1
    function lib:text/core/tables
    data modify storage lib:text_fonts Version set value "3564394154134fd495c2ecf79b0cd9c9177d86b20fa8663e67d3cc437db2c87f"
